name: Deploy to staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BOT_NAME: parcellab-dev-bot
  NODE_VERSION: 22
  SLACK_CHANNEL_STAGING: C03BV5KJJQ7

jobs:
  push_to_s3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          npm run build:site

      - name: AWS - authentication
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Upload to S3
        run: |
          aws s3 cp ./site s3://parcellab-cdn/playground/selection-guide-ui \
            --recursive \
            --cache-control max-age=86400

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3R5S2BJQI4RDS \
            --paths "/playground/selection-guide-ui/*"

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Notify deployment
        uses: darioblanco/slack-deployment@main
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: ${{ env.SLACK_CHANNEL_STAGING }}
          deployment_description: ${{ toJSON(github.event.head_commit.message) }}
          deployment_name: ${{ github.event.repository.name || 'selection-guide-ui' }}
          environment: staging
          owner: ${{ github.event.pusher.name || env.BOT_NAME }}
          package: ${{ github.event.repository.name || 'selection-guide-ui' }}
          ref: ${{ github.ref }}
          repo: ${{ github.repository }}
          sha: ${{ github.sha }}
          status_url: "placeholder"
          url: "placeholder"
          version: ${{ env.SHORT_SHA }}
