name: Deploy to prod (release-tag)

on:
  release:
    types: [published]

env:
  BOT_NAME: parcellab-dev-bot
  SLACK_CHANNEL_PROD: C03C6SP0R61

jobs:
  push_to_s3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          npm run build:site

      - name: AWS - authentication
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Upload versioned files to S3
        run: |
          aws s3 cp ./dist s3://parcellab-cdn/apps/selection-guide-ui/v1/${{ github.event.release.tag_name }} \
            --recursive \
            --cache-control max-age=86400

      - name: Upload latest plugin files to S3
        run: |
          aws s3 cp ./dist s3://parcellab-cdn/js/selection-guide-ui/v1 \
            --recursive \
            --cache-control max-age=86400

      - name: Upload demo page to S3
        run: |
          aws s3 cp ./site s3://parcellab-cdn/apps/selection-guide-ui/v1/demo \
            --recursive \
            --cache-control max-age=86400

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3R5S2BJQI4RDS \
            --paths "/js/selection-guide-ui/v1/*" "/apps/selection-guide-ui/v1/*"

      - name: Notify deployment
        uses: darioblanco/slack-deployment@main
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: ${{ env.SLACK_CHANNEL_PROD }}
          deployment_description: ${{ github.event.release.name }}
          deployment_name: ${{ github.event.repository.name || 'selection-guide-ui' }}
          environment: prod
          owner: ${{ github.actor }}
          package: ${{ github.event.repository.name || 'selection-guide-ui' }}
          ref: ${{ github.ref }}
          repo: ${{ github.repository }}
          sha: ${{ github.sha }}
          status_url: "placeholder"
          url: "placeholder"
          version: ${{ github.event.release.tag_name }}
